### ISSUE TITLE
I'm not able to see any `lib` folder in convex directory.

### ISSUE THREAD

**Issue by Roxy-Jackson** [Gimnath-Perera/convex-next-demo#1]
Hi @Gimnath-Perera 
I installed convex in my nextjs project and found out that `lib` folder is not automatically generated under my `convex` directory, Any idea why?

**Comment by gimnathperera** [comment]
Hi @Roxy-Jackson, when installing `convex` the `lib` folder will not be automatically generated. I created the following file in order to handle required mapping and other async functionalities easily. 
You can read more on Convex and it's features in following link  https://docs.convex.dev/database

**Comment by Roxy-Jackson** [comment]
@Gimnath-Perera thank you. Saves me a lot of time
